TCCME/Models/Patrimonio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCCME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrimonio
    {
        public int PatCodigo { get; set; }
        public string PatNome { get; set; }
        public string PatHistoria { get; set; }
        public string PatEndereco { get; set; }
        public string PatFoto1 { get; set; }
        public string PatFoto2 { get; set; }
        public string PatFoto3 { get; set; }
        public string PatFoto4 { get; set; }
        public string PatFoto5 { get; set; }
        public int PatAcessos { get; set; }
        public string PatHorario { get; set; }
    }
}

TCCME/Controllers/PatrimonioController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCCME.DAO;
using TCCME.Models;

namespace TCCME.Controllers
{
    public class PatrimonioController : Controller
    {

        public ActionResult IndexP()
        {
            PatrimonioDAO dao = new PatrimonioDAO();
            List<Patrimonio> lista = new List<Patrimonio>();           

            lista = dao.getTodosPatrimonios();

            return View(lista);
        }


        public ActionResult Administracao()
        {

            PatrimonioDAO dao = new PatrimonioDAO();
            List<Patrimonio> lista = new List<Patrimonio>();
            lista = dao.getTodosPatrimonios();
            return View(lista);
        }

        public ActionResult Create()
        {

            Usuario usu = (Usuario)Session["usuario"];

            if (usu == null)
                return RedirectToAction("Login", "Moderador");

            CategoriaDAO dao = new CategoriaDAO();
            ViewBag.categorias = dao.getTodasCategorias();

            return View();
        }
        [HttpPost]
        public ActionResult Create(string PatNome, string PatHistoria, string PatEndereco,  string PatFoto1, string PatAcessos)
        {
            PatrimonioDAO dao = new PatrimonioDAO();
            Patrimonio novoPatrimonio = new Patrimonio();

            novoPatrimonio.PatNome = PatNome;
            novoPatrimonio.PatHistoria = PatHistoria;
            novoPatrimonio.PatEndereco = PatEndereco;
            novoPatrimonio.PatFoto1 = PatFoto1;
            novoPatrimonio.PatAcessos = 0;

            dao.AddPatrimonio(novoPatrimonio);

            novoPatrimonio = dao.getTodosPatrimonios().Last();

            HttpFileCollectionBase arquivos = Request.Files;

            if (arquivos.Count > 0)
            {
                string nomeArquivo = novoPatrimonio.PatCodigo + "_" + "Foto1.jpg";
                novoPatrimonio.PatFoto1 = nomeArquivo;
                dao.Alterar(novoPatrimonio);


                string path = Path.Combine(Server.MapPath("~/Uploads/Imagens"), nomeArquivo);
                HttpPostedFileBase file = arquivos[0];
                file.SaveAs(path);
            }

            return RedirectToAction("Administracao");
        }





        public ActionResult Excluir(int? id)

        {
            Usuario usu = (Usuario)Session["usuario"];

            if (usu == null)
                return RedirectToAction("Login", "Moderador");

            PatrimonioDAO dao = new PatrimonioDAO();
            Patrimonio patAtual = dao.getTodosPatrimonios().Find(x => x.PatCodigo == id);

            dao.Remover(patAtual);

            return RedirectToAction("Administracao");

        }





        public ActionResult Edit(int? id)
        {
            Usuario usu = (Usuario)Session["usuario"];

            if (usu == null)
                return RedirectToAction("Login", "Moderador");

            PatrimonioDAO dao = new PatrimonioDAO();
            Patrimonio patAtual = dao.getTodosPatrimonios().Find(x => x.PatCodigo == id);

            return View(patAtual);
        }
        [HttpPost]
        public ActionResult Edit(string PatCodigo, string PatNome, string PatHistoria, string PatEndereco, string PatFoto1)
        {
            PatrimonioDAO dao = new PatrimonioDAO();
            Patrimonio atualPatrimonio = dao.getTodosPatrimonios().Find(x => x.PatCodigo == Convert.ToInt32(PatCodigo));

            atualPatrimonio.PatNome = PatNome;
            atualPatrimonio.PatHistoria = PatHistoria;
            atualPatrimonio.PatEndereco = PatEndereco;
            atualPatrimonio.PatFoto1 = PatFoto1;
            atualPatrimonio.PatAcessos = 0;

            dao.Alterar(atualPatrimonio);

            return RedirectToAction("Administracao");
        }

        public ActionResult Perfil ()
        {
            return View();
        }

	}
}

TCCME/Views/Patrimonio/Administracao.cshtml
@model IEnumerable<TCCME.Models.Patrimonio>
@{
    ViewBag.Title = "Administracao";

}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="~/Content/css/agency.css" rel="stylesheet">
    <link href="~/Content/css/MinhaEstancia2.css" rel="stylesheet" />
   
    <title>Administração</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-1">
                <a class="btn btn-primary" href="@Url.Action("Create","Patrimonio")">Novo <i class="fa fa-plus-square"></i></a>
            </div>
        </div>
    </div> <br /> <br />
    <div class="container" style="background-color: white">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive">
                    <tr>
                        <th class="text-center">Código</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Endereço</th>
                        <th class="text-center">Opões</th>
                    </tr>
                    @foreach (var item in @Model)
                    {
                        <tr>
                            <td>@item.PatCodigo.ToString()</td>
                            <td>@item.PatNome</td>
                            <td>@item.PatEndereco</td>
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("Edit", "Patrimonio", new {id = @item.PatCodigo})" data-toggle="tooltip" title="Editar">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a class="btn btn-primary" href="@Url.Action("Excluir", "Patrimonio", new {id = @item.PatCodigo})" data-toggle="tooltip" title="Excluir">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>
</html>

TCCME/Views/Patrimonio/Create.cshtml
@model  IEnumerable<TCCME.Models.Categoria>
@{
    ViewBag.Title = "Create";

}




<div class="container">
        <div class="row">
          
    <div class="col-md-12">
        <div class="jumbotron">
            <h2>NOVO PATRIMÔNIO</h2>
            <br />
            <form action="@Url.Action("Create","Patrimonio")" method="post" enctype="multipart/form-data">
                <div class="col-md-6">
                    <label>Nome Patrimônio</label>
                    <input type="text" class="form-control" id="PatNome" name="PatNome" /><br />

                    <label>História</label>
                    <textarea rows="4" class="form-control" cols="50" id="PatHistoria" name="PatHistoria"></textarea><br />

                    <label>Endereço</label>
                    <textarea rows="2" cols="50" class="form-control" id="PatEndereco" name="PatEndereco"></textarea><br />

                    <label>Horario de visitação</label>
                    <br />
                    <input type="text" class="form-control" id="PatHorario" name="PatHorario">
                    <br />

                    <label>Categoria</label>
                    <br />
                    <select>
                        @foreach (var item in ViewBag.categorias)
                        {
                            <option value="@item.CatCodigo">@item.CatNome</option>
                        }
                    </select>
                </div>
                <div class="col-md-6">
                    <label>Foto 1</label>
                    <input type="file" class="form-control" id="PatFoto1" name="PatFoto1" /><br />

                    <label>Foto 2</label>
                    <input type="file" class="form-control" id="PatFoto2" name="PatFoto2" /><br />

                    <label>Foto 3</label>
                    <input type="file" class="form-control" id="PatFoto3" name="PatFoto3" /><br />

                    <label>Foto 4</label>
                    <input type="file" class="form-control" id="PatFoto4" name="PatFoto4" /><br />

                    <label>Foto 5</label>
                    <input type="file" class="form-control" id="PatFoto5" name="PatFoto5" /><br />
                </div>
               
                <br />
                <br />
                

                <button class="btn btn-primary 4x btn-block" type="submit" value="Enviar">Enviar</button>
            </form>
            </div>
        </div>
    

</div>
    </div>

TCCME/Views/Patrimonio/Edit.cshtml
@model  TCCME.Models.Patrimonio
@{
    ViewBag.Title = "Edit";
}



<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="jumbotron">

                <h2>Alterar</h2>
                <br />

                <form action="@Url.Action("Edit","Patrimonio")" method="post">

                    <input type="hidden" id="PatCodigo" name="PatCodigo" value="@Model.PatCodigo" />



                    <label>Nome Patrimônio</label>
                    <input type="text" id="PatNome" class="form-control" name="PatNome" value="@Model.PatNome" /><br />

                    <label>História</label>
                    <textarea rows="4" cols="50" class="form-control" id="PatHistoria" name="PatHistoria"> value="@Model.PatHistoria" </textarea><br />

                    <label>Endereço</label>
                    <textarea rows="2" cols="50" class="form-control" id="PatEndereco" name="PatEndereco">value="@Model.PatEndereco" </textarea><br />

                    <label>Horario de visitação</label>
                    <br />
                    <input type="text" class="form-control" id="PatHorario" name="PatHorario" value="@Model.PatHorario">

                    <label>Foto 1</label>
                    <input type="file" id="PatFoto1" class="form-control" name="PatFoto1" value="@Model.PatFoto1" /><br />

                    <label>Foto 2</label>
                    <input type="file" class="form-control" id="PatFoto2" name="PatFoto2" value="@Model.PatFoto2" /><br />

                    <label>Foto 3</label>
                    <input type="file" class="form-control" id="PatFoto3" name="PatFoto3" value="@Model.PatFoto3" /><br />

                    <label>Foto 4</label>
                    <input type="file" class="form-control" id="PatFoto4" name="PatFoto4" value="@Model.PatFoto4"/><br />

                    <label>Foto 5</label>
                    <input type="file" class="form-control" id="PatFoto5" name="PatFoto5" value="@Model.PatFoto5" /><br />


                    <button class="btn btn-primary 4x form-control" type="submit" value="Enviar">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</div>

TCCME/Views/Patrimonio/IndexP.cshtml
@model IEnumerable<TCCME.Models.Patrimonio>
@{
    ViewBag.Title = "Patrimônios";
}



    <h2></h2>

    @foreach (var item in Model)
    {<div class="col-md-8 pats">
        <div class="fotoL bstn-fd-item-cover">
            <img src="~/Content/Uploads/Imagens/@item.PatFoto1" />
        </div>
        <h2 class="titulos">@item.PatNome</h2>
        <p class="ps">@item.PatHistoria.Substring(0, 190) ...</p>

        <a class="btn btn-primary perfil" href="@Url.Action("Perfil", "Patrimonio", new { id = @item.PatCodigo })">PERFIL <i class="fa fa-university"></i></a>
    </div>}

TCCME/Views/Patrimonio/Perfil.cshtml
@model IEnumerable<TCCME.Models.Patrimonio>
@{
    ViewBag.Title = "Perfil";
}

<h2>Perfil</h2>